import keyMirror from "keymirror";
export default keyMirror({
  GOT_HOMEPAGE: null,
  FETCHED_PRODUCTS: null,
  EMPTY_PRODUCTS: null,
  GOT_SUGGESTIONS: null,
  LOGGED_IN: null,
  LOGGED_OUT: null,
  FETCHED_SMALL_POSTER: null,
  FETCH_BANNER: null,
  FETCH_SLIDER: null,
  SEND_CONTACT: null,
  FETCH_BRANDS: null,
  PRODUCT_DETAIL: null,
  WISHLIST: null,
  ERROR: null,
  FETCH_WISHLIST: null,
  FETCH_POPULAR_BRANDS: null,
  REPORT: null,
  LOADING: null,
  CURRENT_LOCATION: null,
  SHOW_PRODUCT_MENU: null,
  SUBSCRIPTION: null,
  API_SUGGEST_US: null,
  GET_PRODUCT_REVIEW: null,
  POST_PRODUCT_REVIEW: null,
  PRODUCT_SEO: null,
  PRICE_GRAPH: null,
  LIVE_PRICE: null,

  MODAL_IMAGE_CAROUSEL: null,
  MODAL_LOCATION: null,
  MODAL_SIDENAV: null,
  RESET_MODAL: null,
  AUTH_MODAL: null,
  DOWNLOAD_APP_MODAL: null,
  NOTIFICATION_MODAL: null,
  REPORT_MODAL: null,
  PRODUCT_REVIEW_MODAL: null,
  SUGGEST_US: null,
  MODAL_PRICE_GRAPH: null,
  CURRENT_LOCATION_MODAL: null,
  NAVIGATE_STORE_MODAL: null,

  UPDATED: null
});
